const requests ={
    generalKnoweledge_TrueFalse_easy : "api.php?amount=30&category=9&difficulty=easy&type=boolean",
    generalKnoweledge_TrueFalse_medium: "api.php?amount=30&category=9&difficulty=medium&type=boolean",
    generalKnoweledge_TrueFalse_hard: "api.php?amount=6&category=9&difficulty=hard&type=boolean",
    generalKnoweledge_multipleChoice_easy : "api.php?amount=50&category=9&difficulty=easy&type=multiple",
    generalKnoweledge_multipleChoice_medium: "api.php?amount=50&category=9&difficulty=medium&type=multiple",
    generalKnoweledge_TrueFalse_easy : "api.php?amount=30&category=9&difficulty=easy&type=boolean",
    generalKnoweledge_multipleChoice_hard: "api.php?amount=50&category=9&difficulty=hard&type=multiple",
    
    Books_TrueFalse_easy : "api.php?amount=20&category=10&difficulty=hard",
    Books_TrueFalse_medium:"api.php?amount=40&category=10&difficulty=medium",
    Books_TrueFalse_hard:"api.php?amount=20&category=10&difficulty=hard",
    Books_multipleChoice_easy : "api.php?amount=20&category=10&difficulty=easy&type=multiple",
    Books_multipleChoice_medium:"api.php?amount=40&category=10&difficulty=medium&type=multiple",
    Books_multipleChoice_hard:"api.php?amount=20&category=10&difficulty=hard&type=multiple",
    history_TrueFalse_easy : "api.php?amount=10&category=23&difficulty=easy&type=boolean",
    historY_TrueFalse_medium : "api.php?amount=20&category=23&difficulty=medium&type=boolean",
    history_TrueFalse_hard: "api.php?amount=8&category=23&difficulty=hard&type=boolean",
    history_multipleChoice_easy : "api.php?amount=50&category=23&difficulty=easy&type=multiple",
    history_multipleChoice_medium : "api.php?amount=50&category=23&difficulty=medium&type=multiple",
    history_multipleChoice_hard: "api.php?amount=50&category=23&difficulty=hard&type=multiple",
    music_TrueFalse_easy: "api.php?amount=10&category=12&difficulty=easy&type=boolean",
    music_TrueFalse_medium: "api.php?amount=20&category=12&difficulty=medium&type=boolean",
    music_TrueFalse_hard: "api.php?amount=5&category=12&difficulty=hard&type=boolean",
    music_multipleChoice_easy: "api.php?amount=50&category=12&difficulty=medium&type=multiple",
    music_TmultipleChoice_medium: "api.php?amount=50&category=12&difficulty=medium&type=multiple",
    music_multipleChoice_hard: "api.php?amount=50&category=12&difficulty=hard&type=multiple",
}